---
- name: Ping Azure VMs
  hosts: azure_vm
  gather_facts: no
  tasks:
    - name: Ping the host
      ansible.builtin.ping:

- name: Install Apache on Azure VMs
  hosts: azure_vm
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

