---
- name: Test Ansible Vault Variables
  hosts: windows
  gather_facts: no
  vars_files:
    - group_vars/password.yml  # or group_vars/all.yml

  tasks:
    - name: Debug the password
      debug:
        msg: "Windows VM password is: {{ windows_vm_password }}"
